app/urls.py
from django.conf.urls import url
from app import views


app_name = "app"

urlpatterns = [
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.user_login, name="login"),
]

django_users/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^app/',include('app.urls')),
    url(r'^logout/$', views.user_logout, name="logout"),
    ]

app/models.py
from django.db import models
from django.contrib.auth.models import User   #Built-in stuff: username email password firstname & lastname

# Create your models here.

class UserProfileInfo(models.Model):

    #take from built-in User we are gonna add our own fields in addition to fields already present in User
    user = models.OneToOneField(User)

    #My add-on fields
    portfolio_site = models.URLField(blank=True) #Not necessarily needed by user to fill it out
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)
    #now we gotta make a folder profile_pics under media
    #install pillow in venv for python images


    def __str__(self):
        return self.user.username

app/forms.py
from django import forms
from django.contrib.auth.models import User
from app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['username','email','password']


class UserProfileInfoForm(forms.ModelForm):
    #Nothing I wanna Modify

    class Meta():
        model = UserProfileInfo
        fields = ['portfolio_site', 'profile_pic']

app/views.py
from django.shortcuts import render
from app.forms import UserForm, UserProfileInfoForm

#Building up the Login Functionality
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required #This is a decorator DUH! see the import path lol
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    return render(request, 'app/index.html')


@login_required  #this DECORATOR makes it compulsory for this functionality to be invoked only when the user is already logged in .!.
def user_logout(request): #Can't use the name logout as its something I imported
    logout(request) #Thanks you django
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False  #By default we set it to False, User ain't registered yet

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        user_profile_info_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and user_profile_info_form.is_valid():

            user = user_form.save(commit=False) #save but don't commit in the database
            user.set_password(user.password)
            user.save()

            profile = user_profile_info_form.save(commit=False)
            profile.user = user #remember that OneToOneField Relation that is defined here

            if 'profile_pic' in request.FILES:                #Do this for all non-textual data like .csv files or images or audio
                profile.profile_pic = request.FILES['profile_pic'] #NOTE: we ain't doing this for the portfolio_site

            profile.save()
            registered = True   #Ok so officially registered and all stuff & shit is figured out

        else:
            print(user_form.errors, user_profile_info_form.errors)



    else:   #Means its a GET Request <3
        user_form = UserForm()
        user_profile_info_form = UserProfileInfoForm()

    context_dict = {'registered':registered, 'user_form':user_form, 'user_profile_info_form':user_profile_info_form }

    return render(request, 'app/registration.html', context = context_dict)


def user_login(request):     #Note that login is something I imported so can't use it as name <3

    if request.method == "POST":
        username = request.POST.get("usern")  #Look the name in <input> in login.html
        password = request.POST.get("pass")     #Look the name in <input> in login.html

        user = authenticate(username=username, password=password)  #Thanks you django <3

        if user: #If user was authenticated!
            if user.is_active:
                login(request,user) #Thanks you django again!
                return HttpResponseRedirect(reverse('index'))
                #Ok so render is like render(request, 'path/to/page.html',context) here HttpResponseRedirect Redirects the user to the
                #HARD-CODED URL given to it as ARGUMENT but hey! remember we don;t hard code URL instead we use dynamic URL TEMPLATE
                #TAGS which map the URL for us and the pay-off is huge if we ever need to change the url we just need to change it
                # in one place i.e. the the urlpatterns!   so I wanna use that same stuff here but here CANNOT use {% url 'index' %}
                # as I want to redirect it at my own index.html so what to do USE reverse() it taken the stuff after url with ''


            else:
                return HttpResponse("INACTIVE USER ACCOUNT!")

        else:
            print("Unauthenticated user")
            print("Username: {} Password: {}".format(username,password))
            return HttpResponse("Invalid Login Details Supplied .!.")


    else: #method wasn't post
        return render(request, "app/login.html")

templates/app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>{% block title %}BASE{% endblock %}</title>
</head>

<body>

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
    <div class="container">
      <a href="{% url 'index' %}" class="navbar-brand">Django</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#NavbarMenu"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="NavbarMenu">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
          </li>
          <li class="nav-item">
              <a href="{% url 'app:register' %}" class="nav-link">Register</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
              <a href="{% url 'logout' %}" class="nav-link">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a href="{% url 'app:login' %}" class="nav-link">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container" style="margin-top: 100px;">
    {% block body %}
    {% endblock %}
  </div>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

templates/app/index.html
{% extends 'app/base.html' %}
{% block title%}Index{% endblock %}

{% block body %}
  <div class="jumbotron">
    <h1>Welcome To the Index Page</h1>
  </div>
{% endblock %}

templates/app/login.html
{% extends 'app/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}
  <div class="jumbotron">
    <form method="post">{% csrf_token %}
      <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" id="username" name="usern" placeholder="Username" class="form-control">
      </div>
      <div class="form-group">
        <label for="pass">Password:</label>
        <input type="password" id="password" name="pass" placeholder="Password" class="form-control">
      </div>
      <input type="submit" value="Login">
    </form>
  </div>
{% endblock %}

templates/app/registration.html
{% extends 'app/base.html' %}
{% block title %}Registration{% endblock %}

{% block body %}

  {% if registered %}
    <div class="jumbotron">
      <h1>Thank You For Registration</h1>
    </div>
  {% else %}
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ user_profile_info_form.as_p }}
      <input type="submit" value="Register" class="btn btn-primary">
    </form>
  {% endif %}
{% endblock %}